steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/api'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting']
