"""
Centralized enum definitions for the trading platform.

All enums used across models should be defined here to ensure consistency
and prevent duplicate definitions with different values.
"""
import enum


# ============================================================================
# Trading Enums
# ============================================================================

class SignalType(str, enum.Enum):
    """Trading signal types generated by strategies."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class OrderSideEnum(str, enum.Enum):
    """Order side enumeration."""
    BUY = "buy"
    SELL = "sell"


class OrderTypeEnum(str, enum.Enum):
    """Order type enumeration."""
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TRAILING_STOP = "trailing_stop"


class OrderStatusEnum(str, enum.Enum):
    """Order status enumeration."""
    NEW = "new"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    DONE_FOR_DAY = "done_for_day"
    CANCELED = "canceled"
    EXPIRED = "expired"
    REPLACED = "replaced"
    PENDING_CANCEL = "pending_cancel"
    PENDING_REPLACE = "pending_replace"
    ACCEPTED = "accepted"
    PENDING_NEW = "pending_new"
    REJECTED = "rejected"
    SUSPENDED = "suspended"
    STOPPED = "stopped"


class TradeType(str, enum.Enum):
    """Trade types."""
    BUY = "buy"
    SELL = "sell"


class TradeStatus(str, enum.Enum):
    """Trade status."""
    PENDING = "pending"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


# ============================================================================
# User & Authentication Enums
# ============================================================================

class UserRole(str, enum.Enum):
    """User roles for authorization."""
    ADMIN = "admin"
    USER = "user"
    VIEWER = "viewer"


# ============================================================================
# Strategy Enums
# ============================================================================

class ExecutionState(str, enum.Enum):
    """Strategy execution states."""
    ACTIVE = "active"
    INACTIVE = "inactive"
    PAUSED = "paused"
    ERROR = "error"
    CIRCUIT_BREAKER = "circuit_breaker"


class LiveStrategyStatus(str, enum.Enum):
    """Live strategy status."""
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"


class BacktestStatus(str, enum.Enum):
    """Backtest execution status."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


# ============================================================================
# Risk Management Enums
# ============================================================================

class RiskRuleType(str, enum.Enum):
    """Types of risk rules."""
    MAX_POSITION_SIZE = "max_position_size"
    MAX_DAILY_LOSS = "max_daily_loss"
    MAX_DRAWDOWN = "max_drawdown"
    MAX_CORRELATION = "max_correlation"
    MAX_LEVERAGE = "max_leverage"
    POSITION_LIMIT = "position_limit"
    SECTOR_LIMIT = "sector_limit"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"


class RiskRuleAction(str, enum.Enum):
    """Actions to take when risk rule is breached."""
    ALERT = "alert"
    BLOCK = "block"
    CLOSE_POSITION = "close_position"
    CLOSE_ALL = "close_all"
    REDUCE_SIZE = "reduce_size"


# ============================================================================
# Notification Enums
# ============================================================================

class NotificationType(str, enum.Enum):
    """Types of notifications."""
    ORDER_FILLED = "order_filled"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_REJECTED = "order_rejected"
    POSITION_OPENED = "position_opened"
    POSITION_CLOSED = "position_closed"
    STRATEGY_SIGNAL = "strategy_signal"
    RISK_BREACH = "risk_breach"
    DAILY_SUMMARY = "daily_summary"
    SYSTEM_ALERT = "system_alert"
    PROFIT_TARGET = "profit_target"
    STOP_LOSS = "stop_loss"


class NotificationChannel(str, enum.Enum):
    """Notification delivery channels."""
    EMAIL = "email"
    IN_APP = "in_app"
    PUSH = "push"
    SMS = "sms"
    WEBHOOK = "webhook"


class NotificationPriority(str, enum.Enum):
    """Notification priority levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


# ============================================================================
# API & Broker Enums
# ============================================================================

class BrokerType(str, enum.Enum):
    """Supported broker types."""
    ALPACA = "alpaca"
    INTERACTIVE_BROKERS = "interactive_brokers"
    TD_AMERITRADE = "td_ameritrade"
    ROBINHOOD = "robinhood"
    COINBASE = "coinbase"
    BINANCE = "binance"


class ApiKeyStatus(str, enum.Enum):
    """API key status."""
    ACTIVE = "active"
    INACTIVE = "inactive"
    EXPIRED = "expired"
    REVOKED = "revoked"


# ============================================================================
# Tax & Portfolio Enums
# ============================================================================

class TaxLotStatus(str, enum.Enum):
    """Tax lot status."""
    OPEN = "open"
    CLOSED = "closed"
    PARTIAL = "partial"


class PerformancePeriod(str, enum.Enum):
    """Performance metric period types."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    YEARLY = "yearly"
    ALL_TIME = "all_time"
