"""
Strategy execution tracking models.
Tracks execution state, signals, and performance metrics.
"""
from datetime import datetime
from typing import Optional
from sqlalchemy import String, Boolean, DateTime, ForeignKey, Text, JSON, Float, Integer, Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func
import uuid

from app.models.base import Base
from app.models.enums import SignalType, ExecutionState



class StrategyExecution(Base):
    """
    Strategy execution tracking model.
    Tracks the execution state and configuration of automated strategies.
    """
    
    __tablename__ = "strategy_executions"
    
    # Primary key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )
    
    # Foreign key to strategy
    strategy_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("strategies.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True
    )
    
    # Execution state
    state: Mapped[ExecutionState] = mapped_column(
        SQLEnum(ExecutionState, values_callable=lambda x: [e.value for e in x]),
        default=ExecutionState.INACTIVE,
        nullable=False,
        index=True
    )
    
    # Execution timestamps
    last_evaluated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        comment="Last time strategy was evaluated"
    )
    
    last_signal_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        comment="Last time a non-HOLD signal was generated"
    )
    
    last_trade_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        comment="Last time a trade was executed"
    )
    
    # Circuit breaker tracking
    trades_today: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="Number of trades executed today"
    )
    
    max_trades_per_day: Mapped[int] = mapped_column(
        Integer,
        default=10,
        nullable=False
    )
    
    loss_today: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False,
        comment="Total loss today in dollars"
    )
    
    max_loss_per_day: Mapped[float] = mapped_column(
        Float,
        default=1000.0,
        nullable=False,
        comment="Maximum allowed loss per day in dollars"
    )
    
    consecutive_losses: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False
    )
    
    max_consecutive_losses: Mapped[int] = mapped_column(
        Integer,
        default=3,
        nullable=False
    )
    
    circuit_breaker_reset_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        comment="When circuit breaker was last reset"
    )
    
    # Error tracking
    last_error: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="Last error message encountered"
    )
    
    error_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="Number of consecutive errors"
    )
    
    # Position tracking
    has_open_position: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether strategy currently has an open position"
    )
    
    current_position_qty: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Current position quantity"
    )
    
    current_position_entry_price: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Entry price of current position"
    )
    
    # Configuration overrides
    config_overrides: Mapped[Optional[dict]] = mapped_column(
        JSON,
        comment="Runtime configuration overrides"
    )
    
    # Dry run mode
    is_dry_run: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="If true, generates signals but doesn't execute trades"
    )
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )
    
    def __repr__(self) -> str:
        return f"<StrategyExecution(id={self.id}, strategy_id={self.strategy_id}, state={self.state})>"


class StrategySignal(Base):
    """
    Historical signals generated by strategies.
    Records all buy/sell/hold signals for audit and analysis.
    """
    
    __tablename__ = "strategy_signals"
    
    # Primary key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )
    
    # Foreign key to strategy
    strategy_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Foreign key to execution
    execution_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("strategy_executions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Signal details
    signal_type: Mapped[SignalType] = mapped_column(
        SQLEnum(SignalType, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        index=True
    )
    
    symbol: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True
    )
    
    # Signal metadata
    signal_strength: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Signal strength/confidence (0-1)"
    )
    
    price_at_signal: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Market price when signal was generated"
    )
    
    # Indicator values at signal time
    indicator_values: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Technical indicator values at signal time"
    )
    
    # Reasoning and execution
    reasoning: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Explanation for the signal"
    )
    
    was_executed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether signal resulted in an executed trade"
    )
    
    order_id: Mapped[Optional[str]] = mapped_column(
        String(36),
        nullable=True,
        comment="Associated order ID if executed (no FK constraint)"
    )
    
    execution_error: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="Error message if execution failed"
    )
    
    # Timestamps
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True
    )
    
    executed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        comment="When the signal was executed as a trade"
    )
    
    def __repr__(self) -> str:
        return f"<StrategySignal(id={self.id}, type={self.signal_type}, symbol={self.symbol})>"


class StrategyPerformance(Base):
    """
    Strategy performance metrics tracking.
    Stores daily and cumulative performance data.
    """
    
    __tablename__ = "strategy_performance"
    
    # Primary key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )
    
    # Foreign key to strategy
    strategy_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Time period
    date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Date of the performance snapshot"
    )
    
    period_type: Mapped[str] = mapped_column(
        String(20),
        default="daily",
        nullable=False,
        comment="Period type: daily, hourly, cumulative"
    )
    
    # Trade statistics
    total_trades: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False
    )
    
    winning_trades: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False
    )
    
    losing_trades: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False
    )
    
    # P&L metrics
    total_pnl: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False,
        comment="Total profit/loss for the period"
    )
    
    gross_profit: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False
    )
    
    gross_loss: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False
    )
    
    # Performance ratios
    win_rate: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Percentage of winning trades"
    )
    
    profit_factor: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Gross profit / Gross loss"
    )
    
    avg_win: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Average winning trade amount"
    )
    
    avg_loss: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Average losing trade amount"
    )
    
    largest_win: Mapped[Optional[float]] = mapped_column(
        Float
    )
    
    largest_loss: Mapped[Optional[float]] = mapped_column(
        Float
    )
    
    # Risk metrics
    max_drawdown: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Maximum drawdown percentage"
    )
    
    sharpe_ratio: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Risk-adjusted return metric"
    )
    
    # Cumulative metrics (for cumulative records)
    cumulative_pnl: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Cumulative P&L since strategy start"
    )
    
    cumulative_trades: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Total trades since strategy start"
    )
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )
    
    def __repr__(self) -> str:
        return f"<StrategyPerformance(id={self.id}, strategy_id={self.strategy_id}, date={self.date})>"
